DEFINE USERNAME = 'mirko';
DEFINE TBSNAME = 'mirkotbs';

CREATE SMALLFILE TABLESPACE &TBSNAME DATAFILE '&TBSNAME' SIZE 50M AUTOEXTEND ON NEXT 5M MAXSIZE 100M;
CREATE USER &USERNAME IDENTIFIED BY &USERNAME DEFAULT TABLESPACE &TBSNAME QUOTA unlimited ON &TBSNAME;

GRANT CREATE SESSION TO &USERNAME;
GRANT CREATE TABLE TO &USERNAME;
GRANT CREATE SEQUENCE TO &USERNAME;
GRANT CREATE VIEW TO &USERNAME;

GRANT aq_administrator_role TO &USERNAME;
GRANT execute ON dbms_aqadm TO &USERNAME;
GRANT execute ON dbms_aq TO &USERNAME;
GRANT execute ON dbms_aqin TO &USERNAME;
GRANT execute ON dbms_aqjms TO &USERNAME;
